// Autogenerated from Pigeon (v4.2.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class Input {
  Input({
    this.displayName,
    required this.instanceId,
    required this.threadId,
    required this.identity,
    required this.endpointUrl,
    required this.acsToken,
  });

  String? displayName;
  int instanceId;
  String threadId;
  String identity;
  String endpointUrl;
  String acsToken;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['displayName'] = displayName;
    pigeonMap['instanceId'] = instanceId;
    pigeonMap['threadId'] = threadId;
    pigeonMap['identity'] = identity;
    pigeonMap['endpointUrl'] = endpointUrl;
    pigeonMap['acsToken'] = acsToken;
    return pigeonMap;
  }

  static Input decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return Input(
      displayName: pigeonMap['displayName'] as String?,
      instanceId: pigeonMap['instanceId']! as int,
      threadId: pigeonMap['threadId']! as String,
      identity: pigeonMap['identity']! as String,
      endpointUrl: pigeonMap['endpointUrl']! as String,
      acsToken: pigeonMap['acsToken']! as String,
    );
  }
}

class _AzureCommunicationUIHostApiCodec extends StandardMessageCodec{
  const _AzureCommunicationUIHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Input) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return Input.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class AzureCommunicationUIHostApi {
  /// Constructor for [AzureCommunicationUIHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AzureCommunicationUIHostApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _AzureCommunicationUIHostApiCodec();

  Future<void> startChatComposite(Input arg_options) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.AzureCommunicationUIHostApi.startChatComposite', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_options]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
}
